---
# tasks file for roles/ansible-demo-server
- name: Import the tower data
  copy:
    src: tower-backup-latest.tar.gz
    dest: /root
- name: Read in initial data
  command: sh setup.sh -e 'restore_backup_file=/root/tower-backup-latest.tar.gz' -r
  args:
    chdir: /root/ansible-tower-setup-3.4.2-1
  when: ansible_installed.stat.exists == False
- name: Create initial repos on awx server
  unarchive:
    src: projects.tar
    dest: /var/lib/awx/projects/
- name: Import nginx module
  command: ansible-galaxy install -r /var/lib/awx/projects/demo/requirements.yml
